# Generated by Django 4.0.1 on 2022-08-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_order_app', '0004_alter_order_kegs_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='kegs',
            new_name='order_items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_status',
            field=models.CharField(default='Open', max_length=10),
        ),
    ]
