# Generated by Django 4.0.1 on 2022-08-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_order_app', '0005_rename_kegs_order_order_items_remove_order_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
