# Generated by Django 4.0.1 on 2022-08-29 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_order_app', '0006_order_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderKegCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keg_count', models.ManyToManyField(blank=True, default=0, to='mcmen_order_app.OrderItem')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='keg_count',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='mcmen_order_app.orderkegcount'),
        ),
    ]
