# Generated by Django 4.0.1 on 2022-08-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_order_app', '0007_orderkegcount_order_keg_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='keg_count',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.DeleteModel(
            name='OrderKegCount',
        ),
    ]
