# Generated by Django 4.0.1 on 2022-08-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_order_app', '0008_alter_order_keg_count_delete_orderkegcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='keg_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
