# Generated by Django 4.0.1 on 2022-09-09 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0026_delete_driver_alter_route_drivers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcmen_inventory_app', '0033_rename_postcomment_brewlogcomment'),
        ('mcmen_order_app', '0009_alter_order_keg_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcmen_dist_app.property'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='beer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcmen_inventory_app.kegs'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='brewery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brewery', to='mcmen_inventory_app.brewery'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcmen_dist_app.property'),
        ),
    ]
