# Generated by Django 4.0.1 on 2022-09-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_order_app', '0010_order_notes_alter_order_manager_alter_order_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
