# Generated by Django 4.0.1 on 2022-09-11 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_order_app', '0011_orderitem_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='keg_count',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcmen_order_app.orderitemcount'),
        ),
    ]
