# Generated by Django 4.0.1 on 2022-02-11 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='drivers',
        ),
        migrations.AddField(
            model_name='truck',
            name='drivers',
            field=models.ForeignKey(default=1979, on_delete=django.db.models.deletion.CASCADE, to='mcmen_dist_app.driver'),
            preserve_default=False,
        ),
    ]
