# Generated by Django 4.0.1 on 2022-02-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0004_remove_truck_drivers_truck_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='drivers',
        ),
        migrations.AddField(
            model_name='truck',
            name='driver',
            field=models.ManyToManyField(to='mcmen_dist_app.Driver'),
        ),
    ]
