# Generated by Django 4.0.1 on 2022-02-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0006_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Truck',
            new_name='Route',
        ),
    ]
