# Generated by Django 4.0.1 on 2022-02-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0007_rename_truck_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lat',
            field=models.CharField(default=99.999, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='lng',
            field=models.CharField(default=99.999, max_length=20),
            preserve_default=False,
        ),
    ]
