# Generated by Django 4.0.1 on 2022-02-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0008_property_lat_property_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='lng',
            field=models.FloatField(max_length=20),
        ),
    ]
