# Generated by Django 4.0.1 on 2022-02-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0009_alter_property_lat_alter_property_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='lat',
            new_name='latX',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='lng',
            new_name='lngX',
        ),
    ]
