# Generated by Django 4.0.1 on 2022-03-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0011_rename_latx_property_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='notes',
            field=models.TextField(max_length=500),
        ),
    ]
