# Generated by Django 4.0.1 on 2022-03-02 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0012_property_images_alter_property_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=300),
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('date_posted', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcmen_dist_app.driver')),
                ('post_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mcmen_dist_app.article')),
            ],
        ),
    ]
