# Generated by Django 4.0.1 on 2022-03-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0013_alter_article_text_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='com_counter',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
