# Generated by Django 4.0.1 on 2022-03-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0014_article_com_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='driver',
            new_name='drivers',
        ),
        migrations.RemoveField(
            model_name='route',
            name='mech_record',
        ),
    ]
