# Generated by Django 4.0.1 on 2022-03-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0015_rename_driver_route_drivers_remove_route_mech_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='com_counter',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='com_counter',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
