# Generated by Django 4.0.1 on 2022-03-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0018_images_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='article',
            name='com_counter',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
