# Generated by Django 4.0.1 on 2022-05-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0019_alter_images_options_article_com_counter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('truck_num', 'day')},
        ),
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.ImageField(default='uploaded_files/images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
