# Generated by Django 4.0.1 on 2022-05-26 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcmen_dist_app', '0020_alter_route_options_alter_property_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_num',
            field=models.CharField(max_length=20),
        ),
    ]
