# Generated by Django 4.0.1 on 2022-05-26 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0021_remove_driver_schedule_alter_article_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='com_counter',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcmen_dist_app.driver'),
        ),
    ]
