# Generated by Django 4.0.1 on 2022-07-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0023_remove_postcomment_com_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
