# Generated by Django 4.0.1 on 2022-08-31 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcmen_dist_app', '0025_alter_article_pub_date_alter_postcomment_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.AlterField(
            model_name='route',
            name='drivers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
