# Generated by Django 4.0.1 on 2022-05-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcmen_dist_app', '0020_alter_route_options_alter_property_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('nick_name', models.CharField(max_length=20)),
                ('phone_num', models.IntegerField()),
            ],
            options={
                'ordering': ('nick_name',),
            },
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_num', models.IntegerField()),
                ('brewers', models.ManyToManyField(to='mcmen_inventory_app.Brewer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcmen_dist_app.property')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Kegs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer', models.CharField(max_length=30)),
                ('brew_date', models.DateField()),
                ('category', models.CharField(max_length=20)),
                ('brewery', models.ManyToManyField(to='mcmen_inventory_app.Brewery')),
            ],
            options={
                'ordering': ('beer',),
            },
        ),
    ]
