# Generated by Django 4.0.1 on 2022-05-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewer',
            options={'ordering': ('last_name',)},
        ),
        migrations.AlterField(
            model_name='brewery',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
