# Generated by Django 4.0.1 on 2022-05-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0003_alter_brewery_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegs',
            name='quantity',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kegs',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='phone_num',
            field=models.CharField(max_length=15),
        ),
    ]
