# Generated by Django 4.0.1 on 2022-05-20 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0004_kegs_quantity_kegs_size_alter_brewery_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegs',
            name='size',
        ),
    ]
