# Generated by Django 4.0.1 on 2022-05-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0005_remove_kegs_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kegs',
            options={'ordering': ('beer',), 'verbose_name_plural': 'Kegs'},
        ),
        migrations.AlterField(
            model_name='brewer',
            name='phone_num',
            field=models.CharField(max_length=15),
        ),
    ]
