# Generated by Django 4.0.1 on 2022-05-26 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0006_alter_kegs_options_alter_brewer_phone_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewer',
            options={'ordering': ('nick_name',)},
        ),
    ]
