# Generated by Django 4.0.1 on 2022-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0022_remove_article_com_counter_alter_article_author'),
        ('mcmen_inventory_app', '0007_alter_brewer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=30)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('beer', models.ManyToManyField(to='mcmen_inventory_app.Kegs')),
                ('property', models.ManyToManyField(to='mcmen_dist_app.Property')),
            ],
        ),
    ]
