# Generated by Django 4.0.1 on 2022-05-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0009_alter_order_options_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveBigIntegerField(default=10),
            preserve_default=False,
        ),
    ]
