# Generated by Django 4.0.1 on 2022-05-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0010_order_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterField(
            model_name='kegs',
            name='quantity',
            field=models.PositiveBigIntegerField(default=10),
            preserve_default=False,
        ),
    ]
