# Generated by Django 4.0.1 on 2022-05-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0011_alter_order_options_alter_kegs_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
