# Generated by Django 4.0.1 on 2022-05-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0023_remove_postcomment_com_counter'),
        ('mcmen_inventory_app', '0013_order_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('order_date',)},
        ),
        migrations.AddField(
            model_name='order',
            name='brewery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='brewery', to='mcmen_inventory_app.brewery'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='beer',
        ),
        migrations.AddField(
            model_name='order',
            name='beer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mcmen_inventory_app.kegs'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='property',
        ),
        migrations.AddField(
            model_name='order',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mcmen_dist_app.property'),
            preserve_default=False,
        ),
    ]
