# Generated by Django 4.0.1 on 2022-05-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0014_alter_order_options_order_brewery_remove_order_beer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='beer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='brewery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='property',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
