# Generated by Django 4.0.1 on 2022-05-26 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0023_remove_postcomment_com_counter'),
        ('mcmen_inventory_app', '0015_alter_order_options_remove_order_beer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('order_date',)},
        ),
        migrations.AddField(
            model_name='order',
            name='beer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mcmen_inventory_app.kegs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='brewery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='brewery', to='mcmen_inventory_app.brewery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mcmen_dist_app.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveBigIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=0.0004945598417408506, max_length=10),
            preserve_default=False,
        ),
    ]
