# Generated by Django 4.0.1 on 2022-05-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0016_alter_order_options_order_beer_order_brewery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='brewery',
            new_name='brewery_connected',
        ),
    ]
