# Generated by Django 4.0.1 on 2022-05-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0017_rename_brewery_order_brewery_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='beer',
            field=models.CharField(max_length=30),
        ),
    ]
