# Generated by Django 4.0.1 on 2022-05-27 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0018_alter_order_beer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='brewery_connected',
            new_name='brewery',
        ),
        migrations.AlterField(
            model_name='order',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcmen_inventory_app.kegs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
