# Generated by Django 4.0.1 on 2022-06-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0019_rename_brewery_connected_order_brewery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegs',
            name='updated',
            field=models.DateField(null=True),
        ),
    ]
