# Generated by Django 4.0.1 on 2022-07-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0022_proporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegs',
            name='updated',
            field=models.DateField(auto_now=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateField(auto_now=True, default='2000-01-01'),
            preserve_default=False,
        ),
    ]
