# Generated by Django 4.0.1 on 2022-07-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0023_alter_kegs_updated_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropOrder',
        ),
    ]
