# Generated by Django 4.0.1 on 2022-07-14 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_dist_app', '0025_alter_article_pub_date_alter_postcomment_author_and_more'),
        ('mcmen_inventory_app', '0024_delete_proporder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=30)),
                ('order_date', models.DateField()),
                ('updated', models.DateField(null=True)),
                ('status', models.CharField(default='Open', max_length=10)),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcmen_inventory_app.brewery')),
                ('kegs', models.ManyToManyField(to='mcmen_inventory_app.Order')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcmen_dist_app.property')),
            ],
            options={
                'ordering': ('order_date',),
            },
        ),
    ]
