# Generated by Django 4.0.1 on 2022-07-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0025_proporder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='brewers',
        ),
        migrations.DeleteModel(
            name='Brewer',
        ),
    ]
