# Generated by Django 4.0.1 on 2022-08-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0028_remove_proporder_brewery_remove_proporder_kegs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='inv_view',
        ),
    ]
