# Generated by Django 4.0.1 on 2022-08-31 01:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcmen_inventory_app', '0029_remove_brewery_inv_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='brewers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
