# Generated by Django 4.0.1 on 2022-08-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_user_app', '0003_userprofile_view_pref'),
        ('mcmen_inventory_app', '0030_brewery_brewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='brewers',
            field=models.ManyToManyField(blank=True, to='mcmen_user_app.UserProfile'),
        ),
    ]
