# Generated by Django 4.0.1 on 2022-08-31 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0031_alter_brewery_brewers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=300)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=300)),
                ('date_posted', models.DateField(auto_now=True)),
                ('post_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mcmen_inventory_app.brewlog')),
            ],
        ),
    ]
