# Generated by Django 4.0.1 on 2022-09-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0032_brewlog_postcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComment',
            new_name='BrewLogComment',
        ),
    ]
