# Generated by Django 4.0.1 on 2022-09-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0034_comingsoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='comingsoon',
            name='brewery',
            field=models.ManyToManyField(to='mcmen_inventory_app.Brewery'),
        ),
    ]
