# Generated by Django 4.0.1 on 2022-09-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_inventory_app', '0036_alter_comingsoon_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kegs',
            old_name='category',
            new_name='sku',
        ),
    ]
