# Generated by Django 4.0.1 on 2022-07-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmen_user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nick_name',
        ),
    ]
